
name: Metrics CI Integrations Actions

on:
  push:
    branches: main

jobs:
  release_actions:
    name: Release Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Configure GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          file-name: hash.sha256.txt

      - name: Archive release hash
        run: tar -czvf hash.sha256.tar.gz hash.sha256.txt

      - name: Create release
        run: gh release create test-release test.txt.zip hash.sha256.tar.gz --prerelease --title 'Test release'
