
name: Test

on:
  push:
    branches: main

jobs:
  ci-integrations-generate-linux-sha-actions:
    name: CI Integrations Generate Linux SHA-256 Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
      - name: Create archive
        run: tar -czvf my/ci_integrations_linux.tgz my/ci_integrations_linux
      
      - name: Generate SHA-256 Hash
        run: shasum my/ci_integrations_linux.tgz > my/ci_integrations_linux.tgz.sha256

      - name: Upload SHA-256 Hash Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci_integrations_linux.tgz.sha256
          path: my/ci_integrations_linux.tgz.sha256
          if-no-files-found: error

  release_actions:
    name: Release Actions
    runs-on: ubuntu-latest
    needs: [ ci-integrations-generate-linux-sha-actions ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Configure GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download CI Integrations Linux SHA-256 Hash
        uses: actions/download-artifact@v2
        with:
          name: ci_integrations_linux.tgz.sha256
          path: my/

      - name: Delete release
        run: |
          gh release delete test-release -y
          git push --delete origin test-release

      - name: Create release
        run: gh release create test-release my/ci_integrations_linux my/ci_integrations_linux.tgz.sha256 --prerelease --title 'Test release'
